# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections: 
    - conn_id: mlflow_default
      conn_type: http
      conn_host: mlflow
      conn_port: 5001
      conn_extra:
        endpoint: ""
    - conn_id: minio_default
      conn_type: s3
      conn_host: http://minio:9000
      conn_login: minioadmin
      conn_password: minioadmin
      conn_extra:
        endpoint_url: http://minio:9000
        aws_access_key_id: minioadmin
        aws_secret_access_key: minioadmin
    - conn_id: redis_default
      conn_type: redis
      conn_host: redis
      conn_port: 6379
      conn_extra:
        db: 0
  pools: []
  variables:
    - variable_name: MLFLOW_TRACKING_URI
      variable_value: http://mlflow:5001
    - variable_name: AWS_ACCESS_KEY_ID
      variable_value: minioadmin
    - variable_name: AWS_SECRET_ACCESS_KEY
      variable_value: minioadmin
    - variable_name: MLFLOW_S3_ENDPOINT_URL
      variable_value: http://minio:9000